### ISSUE TITLE
Error after copying the sample code

### ISSUE THREAD

**Issue by renceInbox** [yakuhzi/action-ssh-agent#3]
Hi trying this action to add my ssh keys but it returns an error. I followed the sample code and run it but it returns an error.

![Screenshot from 2020-02-27 23-19-06](https://user-images.githubusercontent.com/35565900/75457632-aaf08c80-59b7-11ea-9079-19ca98d1ffce.png)

**Comment by yakuhzi** [comment]
Did you used this action with GitHub Actions? Can you show your workflow file? It seems like you are cloning my Repo on branch master and trying to run the main file, which is only available after a npm run build or within the releases/v1 branch.

**Comment by renceInbox** [comment]
Hi @yakuhzi , thanks for replying. 

I am trying to use this to copy my ssh keys like this
![Screenshot from 2020-02-28 16-32-02](https://user-images.githubusercontent.com/35565900/75524437-d8394b00-5a48-11ea-861a-5bfe78408dad.png)


I am using `act` to run the workflow in my local and this is the result
![asdkaslkd](https://user-images.githubusercontent.com/35565900/75524472-f0a96580-5a48-11ea-9d5d-74ad24045825.png)

**Comment by yakuhzi** [comment]
It seems like this is an issue with either Ubuntu or `act`, as my workflows using this action are all running on macOS without issues. I tested it with a new repository using Ubuntu as action host and ran into an other issue: 

```
Error: Command failed: ssh-add -K /home/runner/.ssh/id_rsa
Could not open a connection to your authentication agent.
```

**Comment by renceInbox** [comment]
Hi @yakuhzi Let me try this tomorrow on my mac to confirm.

**Comment by la-pieuvre** [comment]
Hi, I have the same issue on mac
<img width="930" alt="Screenshot 2020-05-14 at 16 17 45" src="https://user-images.githubusercontent.com/817367/81945482-74adcb00-95fe-11ea-8307-fa84848e9cec.png">
with this workflow : 
<img width="785" alt="Screenshot 2020-05-14 at 16 24 32" src="https://user-images.githubusercontent.com/817367/81946230-66ac7a00-95ff-11ea-8807-9ccda8e88e1a.png">

**Comment by yakuhzi** [comment]
Can you check if it's resolved with the latest release?
