### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by cketant** [yakuhzi/action-ssh-agent#6]
Readme has the wrong labels for the inputs.

**Comment by yakuhzi** [comment]
No they are right. I'm using them exactly as they are in the README.

**Comment by ghost** [comment]
Sorry @yakuhzi, they are not correct. I'm getting this error right now

<img width="874" alt="image" src="https://user-images.githubusercontent.com/871198/161626584-6fba4278-ab45-4deb-be2c-87e47b05690c.png">

The correct ones should be:
* `ssh-public-key` and
* `ssh-private-key`

as configured [here](https://github.com/yakuhzi/setup-ssh-agent/blob/master/action.yml#L5-L10).

**Comment by yakuhzi** [comment]
Ah I see sorry, so it is wrong in the `action.yml` file and not in the `README`. I will fix it and release a new version.

**Comment by yakuhzi** [comment]
I published a new [release](https://github.com/yakuhzi/setup-ssh-agent/releases/tag/v2.0.0) of this package in order to resolve this issue. Note that I have changed the major version, as the change includes some breaking changes due to the change of the naming of the input parameters.
